import React from "react";
import { ActivityIndicator, ScrollView, StyleSheet, Text, View } from "react-native";
import { useLocalSearchParams } from "expo-router";
import { Feather } from "@expo/vector-icons";
import { customFetch } from "@workspace/api-client-react";
import { useQuery } from "@tanstack/react-query";
import { useColors } from "@/hooks/useColors";

export default function AdminMemberDetailScreen() {
  const colors = useColors();
  const { id } = useLocalSearchParams<{ id: string }>();
  const { data, isLoading } = useQuery({ queryKey: ["admin", "member", id], queryFn: () => customFetch<{ member: { nickname: string; email: string; statusMessage: string | null; notificationEnabled: boolean; talkAnalysisEnabled: boolean; createdAt: string }; sections: { fan: { level: number; xp: number; stats: Record<string, number> } | null; mode: { currentMode: string; starUnlocked: boolean } | null; star: Array<{ displayName: string; level: number; xp: number; category: string; ownershipStatus: string }>; nft: Array<{ displayName: string; ownershipStatus: string }>; wallets: Array<{ walletAddress: string; chainId: number; verifiedAt: string | null }>; activity: { postCount: number; reportCount: number; blocks: Array<{ blockerUserId: string; blockedUserId: string; createdAt: string }> } } }>(`/api/admin/members/${id}`, { responseType: "json" }) });
  if (isLoading) return <View style={[styles.center, { backgroundColor: colors.background }]}><ActivityIndicator color={colors.primary} /></View>;
  if (!data) return <View style={[styles.center, { backgroundColor: colors.background }]}><Text style={{ color: colors.foreground }}>회원을 찾을 수 없습니다.</Text></View>;
  const m = data.member;
  return <ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={styles.container}><View style={[styles.hero, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.avatar, { backgroundColor: colors.primary + "22" }]}><Feather name="user" size={28} color={colors.primary} /></View><Text style={[styles.title, { color: colors.foreground }]}>{m.nickname}</Text><Text style={[styles.email, { color: colors.mutedForeground }]}>{m.email}</Text><Text style={[styles.meta, { color: colors.mutedForeground }]}>가입일 {new Date(m.createdAt).toLocaleDateString("ko-KR")}</Text></View><Section title="계정 상태" colors={colors}><Row label="알림" value={m.notificationEnabled ? "사용" : "중지"} colors={colors} /><Row label="대화 분석" value={m.talkAnalysisEnabled ? "사용" : "중지"} colors={colors} /><Row label="상태 메시지" value={m.statusMessage || "없음"} colors={colors} /></Section><Section title="AnotherMe 상태" colors={colors}><Row label="현재 모드" value={data.sections.mode?.currentMode ?? "정보 없음"} colors={colors} /><Row label="STAR 해금" value={data.sections.mode?.starUnlocked ? "예" : "아니오"} colors={colors} /><Row label="FAN 레벨" value={data.sections.fan ? `Lv.${data.sections.fan.level} · ${data.sections.fan.xp} XP` : "프로필 없음"} colors={colors} /></Section><Section title="STAR·NFT" colors={colors}>{data.sections.star.length === 0 ? <Text style={{ color: colors.mutedForeground }}>장착·보유 STAR가 없습니다.</Text> : data.sections.star.map((star) => <Row key={star.displayName} label={star.displayName} value={`Lv.${star.level} · ${star.category} · ${star.ownershipStatus}`} colors={colors} />)}</Section><Section title="지갑" colors={colors}>{data.sections.wallets.length === 0 ? <Text style={{ color: colors.mutedForeground }}>연결된 지갑이 없습니다.</Text> : data.sections.wallets.map((wallet) => <Row key={wallet.walletAddress} label={`Chain ${wallet.chainId}`} value={`${wallet.walletAddress.slice(0, 6)}…${wallet.walletAddress.slice(-4)}`} colors={colors} />)}</Section><Section title="활동·운영" colors={colors}><Row label="작성 게시물" value={String(data.sections.activity.postCount)} colors={colors} /><Row label="게시물 신고" value={String(data.sections.activity.reportCount)} colors={colors} /><Row label="차단 관계" value={String(data.sections.activity.blocks.length)} colors={colors} /></Section></ScrollView>;
}
function Section({ title, colors, children }: { title: string; colors: ReturnType<typeof useColors>; children: React.ReactNode }) { return <View style={[styles.section, { backgroundColor: colors.card, borderColor: colors.border }]}><Text style={[styles.sectionTitle, { color: colors.foreground }]}>{title}</Text>{children}</View>; }
function Row({ label, value, colors }: { label: string; value: string; colors: ReturnType<typeof useColors> }) { return <View style={styles.row}><Text style={{ color: colors.mutedForeground }}>{label}</Text><Text style={[styles.value, { color: colors.foreground }]}>{value}</Text></View>; }
const styles = StyleSheet.create({ container: { padding: 18, gap: 12 }, center: { flex: 1, alignItems: "center", justifyContent: "center" }, hero: { borderWidth: 1, borderRadius: 18, padding: 20, alignItems: "center", gap: 8 }, avatar: { width: 58, height: 58, borderRadius: 18, alignItems: "center", justifyContent: "center" }, title: { fontSize: 23, fontWeight: "800" }, email: { fontSize: 12 }, meta: { fontSize: 11 }, section: { borderWidth: 1, borderRadius: 16, padding: 16, gap: 12 }, sectionTitle: { fontSize: 17, fontWeight: "700" }, row: { gap: 4 }, value: { fontSize: 14, fontWeight: "600" } });
