import React from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useLocalSearchParams } from "expo-router";
import { Feather } from "@expo/vector-icons";
import { useColors } from "@/hooks/useColors";
import { useNftAdmin } from "@/hooks/useNftAdmin";
import { useQuery } from "@tanstack/react-query";
import { customFetch } from "@workspace/api-client-react";
import { useMutation, useQueryClient } from "@tanstack/react-query";

export default function AdminIpProfileDetailScreen() {
  const colors = useColors();
  const { id } = useLocalSearchParams<{ id: string }>();
  const { collections, isLoading } = useNftAdmin();
  const item = collections.find((entry) => entry.id === id);
  const { data: stages = [] } = useQuery({ queryKey: ["admin", "nft-stages", id], enabled: !!id, queryFn: () => customFetch<Array<{ stageKey: string; minLevel: number; title: string; description: string; status: string; imageUrl?: string | null }>>(`/api/nft/collections/${id}/evolution`, { responseType: "json" }) });
  if (isLoading) return <View style={[styles.center, { backgroundColor: colors.background }]}><ActivityIndicator color={colors.primary} /></View>;
  if (!item) return <View style={[styles.center, { backgroundColor: colors.background }]}><Text style={{ color: colors.foreground }}>IP를 찾을 수 없습니다.</Text></View>;
  return <ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={styles.container}><View style={[styles.hero, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.icon, { backgroundColor: colors.primary + "22" }]}><Feather name="user" size={28} color={colors.primary} /></View><Text style={[styles.title, { color: colors.foreground }]}>{item.ipName || item.name}</Text><Text style={[styles.meta, { color: colors.mutedForeground }]}>{item.category} · Chain {item.chainId}</Text></View><Section title="IP 기본 정보" colors={colors}><Row label="컬렉션" value={item.name} colors={colors} /><Row label="컨트랙트" value={`${item.contractAddress.slice(0, 8)}…${item.contractAddress.slice(-6)}`} colors={colors} /><Row label="상태" value={item.status} colors={colors} /><Row label="AI 분석" value={item.aiAnalyzedAt ? "완료" : "대기"} colors={colors} /></Section><Section title="성장 RPG" colors={colors}><Text style={{ color: colors.mutedForeground }}>레벨별 성장 단계와 캐릭터 외형 준비 상태입니다.</Text><Row label="역할" value={item.roleName ?? "미설정"} colors={colors} /><Row label="세계관" value={item.worldStyle ?? "미설정"} colors={colors} />{stages.length === 0 ? <Text style={{ color: colors.mutedForeground }}>생성된 성장 단계가 없습니다.</Text> : stages.map((stage) => <StageEditor key={stage.stageKey} collectionId={String(id)} stage={stage} colors={colors} />)}</Section></ScrollView>;
}

function StageEditor({ collectionId, stage, colors }: { collectionId: string; stage: { stageKey: string; minLevel: number; title: string; description: string; status: string; imageUrl?: string | null }; colors: ReturnType<typeof useColors> }) {
  const client = useQueryClient();
  const [level, setLevel] = React.useState(String(stage.minLevel));
  const [title, setTitle] = React.useState(stage.title);
  const [description, setDescription] = React.useState(stage.description);
  const [imageUrl, setImageUrl] = React.useState(stage.imageUrl ?? "");
  const save = useMutation({ mutationFn: (status?: string) => customFetch(`/api/admin/nft/collections/${collectionId}/evolution/${stage.stageKey}`, { method: "PATCH", responseType: "json", body: JSON.stringify({ minLevel: Number(level), title, description, imageUrl: imageUrl.trim() || null, ...(status ? { status } : {}) }) }), onSuccess: () => client.invalidateQueries({ queryKey: ["admin", "nft-stages", collectionId] }) });
  return <View style={[styles.stage, { borderColor: colors.border }]}><Text style={[styles.stageHeading, { color: colors.foreground }]}>Lv.{stage.minLevel} · {stage.title} · {stage.status}</Text><TextInput value={level} onChangeText={setLevel} keyboardType="number-pad" placeholder="최소 레벨" placeholderTextColor={colors.mutedForeground} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} /><TextInput value={title} onChangeText={setTitle} placeholder="단계명" placeholderTextColor={colors.mutedForeground} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} /><TextInput multiline value={description} onChangeText={setDescription} placeholder="단계 설명" placeholderTextColor={colors.mutedForeground} style={[styles.textarea, { color: colors.foreground, borderColor: colors.border }]} /><TextInput value={imageUrl} onChangeText={setImageUrl} placeholder="외형 이미지 URL (선택)" placeholderTextColor={colors.mutedForeground} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} /><View style={styles.actions}><Pressable disabled={save.isPending} onPress={() => void save.mutateAsync(undefined)} style={[styles.saveButton, { backgroundColor: colors.secondary, opacity: save.isPending ? 0.5 : 1 }]}><Text style={{ color: colors.foreground }}>{save.isPending ? "저장 중…" : "단계 저장"}</Text></Pressable>{stage.status === "draft" ? <Pressable disabled={save.isPending} onPress={() => void save.mutateAsync("approved")} style={[styles.saveButton, { backgroundColor: colors.primary }]}><Text style={{ color: colors.primaryForeground }}>승인</Text></Pressable> : null}{stage.status === "approved" ? <Pressable disabled={save.isPending} onPress={() => void save.mutateAsync("published")} style={[styles.saveButton, { backgroundColor: colors.primary }]}><Text style={{ color: colors.primaryForeground }}>게시</Text></Pressable> : null}</View></View>;
}
function Section({ title, colors, children }: { title: string; colors: ReturnType<typeof useColors>; children: React.ReactNode }) { return <View style={[styles.section, { backgroundColor: colors.card, borderColor: colors.border }]}><Text style={[styles.sectionTitle, { color: colors.foreground }]}>{title}</Text>{children}</View>; }
function Row({ label, value, colors }: { label: string; value: string; colors: ReturnType<typeof useColors> }) { return <View style={styles.row}><Text style={{ color: colors.mutedForeground }}>{label}</Text><Text style={[styles.value, { color: colors.foreground }]}>{value}</Text></View>; }
const styles = StyleSheet.create({ container: { padding: 18, gap: 12 }, center: { flex: 1, alignItems: "center", justifyContent: "center" }, hero: { borderWidth: 1, borderRadius: 18, padding: 20, alignItems: "center", gap: 8 }, icon: { width: 58, height: 58, borderRadius: 18, alignItems: "center", justifyContent: "center" }, title: { fontSize: 23, fontWeight: "800" }, meta: { fontSize: 12 }, section: { borderWidth: 1, borderRadius: 16, padding: 16, gap: 12 }, sectionTitle: { fontSize: 17, fontWeight: "700" }, row: { gap: 4 }, value: { fontSize: 14, fontWeight: "600" }, stage: { borderWidth: 1, borderRadius: 12, padding: 11, gap: 7 }, stageHeading: { fontSize: 14, fontWeight: "700" }, input: { minHeight: 40, borderWidth: 1, borderRadius: 9, paddingHorizontal: 10 }, textarea: { minHeight: 80, borderWidth: 1, borderRadius: 9, padding: 10, textAlignVertical: "top" }, actions: { flexDirection: "row", gap: 8 }, saveButton: { borderRadius: 9, minHeight: 38, alignItems: "center", justifyContent: "center", paddingHorizontal: 12 } });
