import { Router, type IRouter } from "express";
import { and, eq, or } from "drizzle-orm";
import { db } from "@workspace/db";
import {
  chatRoomMembersTable,
  chatRoomsTable,
  dungeonSessionsTable,
  friendshipsTable,
  type DungeonState,
} from "@workspace/db";
import { requireAuth } from "../lib/auth";
import { buildInitialParty, getOrCreateDmUser, runDungeonTurn } from "../lib/dungeon";
import { roomWithMeta } from "./rooms";

const router: IRouter = Router();

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

// Create a new dungeon: a "dungeon" chat room with the chosen friends plus the
// AI Dungeon Master bot, a fresh game session, and a fire-and-forget opening
// scene generated by the DM.
router.post("/dungeons", requireAuth, async (req, res): Promise<void> => {
  const userId = req.dbUser!.id;
  const { name, memberIds, theme } = req.body as {
    name?: string;
    memberIds?: unknown;
    theme?: string;
  };

  if (!Array.isArray(memberIds)) {
    res.status(400).json({ error: "memberIds is required" });
    return;
  }

  const requestedIds = Array.from(
    new Set(
      memberIds.filter(
        (id): id is string => typeof id === "string" && UUID_RE.test(id) && id !== userId,
      ),
    ),
  );

  // Only allow inviting people who are actually friends with the requester.
  let invitedIds: string[] = [];
  if (requestedIds.length > 0) {
    const friendships = await db
      .select()
      .from(friendshipsTable)
      .where(or(eq(friendshipsTable.userAId, userId), eq(friendshipsTable.userBId, userId)));
    const friendIds = new Set(
      friendships.map((f) => (f.userAId === userId ? f.userBId : f.userAId)),
    );
    const invalid = requestedIds.filter((id) => !friendIds.has(id));
    if (invalid.length > 0) {
      res.status(403).json({ error: "Can only invite friends to a dungeon" });
      return;
    }
    invitedIds = requestedIds;
  }

  const humanIds = [userId, ...invitedIds];
  const dmUserId = await getOrCreateDmUser();

  const party = await buildInitialParty(humanIds);
  const state: DungeonState = {
    scene: "던전 입구",
    party,
    enemies: [],
    goals: [],
    points: 0,
    turn: 0,
    ended: false,
    choices: [],
    lastTurnEvents: [],
  };

  // Create room + members + session atomically so a mid-way failure cannot
  // leave an orphaned room or a memberless dungeon.
  const room = await db.transaction(async (tx) => {
    const [created] = await tx
      .insert(chatRoomsTable)
      .values({
        type: "dungeon",
        name: name?.trim() || "던전 탐험",
        ownerId: userId,
      })
      .returning();

    await tx.insert(chatRoomMembersTable).values(
      [...humanIds, dmUserId].map((uid) => ({ roomId: created.id, userId: uid })),
    );

    await tx.insert(dungeonSessionsTable).values({
      roomId: created.id,
      theme: theme?.trim() || "fantasy",
      status: "active",
      state,
    });

    return created;
  });

  const result = await roomWithMeta(room.id, userId);
  res.status(201).json(result);

  // Generate the opening scene without blocking the response.
  void runDungeonTurn(room.id, null, req.log).catch((err) =>
    req.log.error({ err, roomId: room.id }, "Dungeon opening turn failed"),
  );
});

// Fetch the current party/game state for a dungeon room (membership required).
router.get("/dungeons/:id", requireAuth, async (req, res): Promise<void> => {
  const userId = req.dbUser!.id;
  const raw = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id;

  const [member] = await db
    .select()
    .from(chatRoomMembersTable)
    .where(and(eq(chatRoomMembersTable.roomId, raw), eq(chatRoomMembersTable.userId, userId)));
  if (!member) {
    res.status(403).json({ error: "Not a member" });
    return;
  }

  const [session] = await db
    .select()
    .from(dungeonSessionsTable)
    .where(eq(dungeonSessionsTable.roomId, raw));
  if (!session) {
    res.status(404).json({ error: "Not a dungeon" });
    return;
  }

  res.json({
    roomId: raw,
    theme: session.theme,
    status: session.status,
    scene: session.state.scene,
    turn: session.state.turn,
    ended: session.state.ended,
    points: session.state.points ?? 0,
    goals: session.state.goals ?? [],
    party: session.state.party,
    enemies: session.state.enemies ?? [],
    choices: session.state.choices ?? [],
    lastTurnEvents: session.state.lastTurnEvents ?? [],
    lastNarrativeMessageId: session.state.lastNarrativeMessageId,
  });
});

export default router;
