import { Router, type IRouter } from "express";
import { and, desc, eq } from "drizzle-orm";
import { z } from "zod/v4";
import { db, fanBroadcastsTable, fanCommunitiesTable, fanCommunityMembersTable, fanMissionsTable, fanMissionParticipantsTable } from "@workspace/db";
import { requireAuth } from "../lib/auth";
const router: IRouter = Router();
const id = (value: unknown) => typeof value === "string" && z.uuid().safeParse(value).success ? value : null;
async function isMember(communityId: string, userId: string) { const [row] = await db.select({ role: fanCommunityMembersTable.role }).from(fanCommunityMembersTable).where(and(eq(fanCommunityMembersTable.communityId, communityId), eq(fanCommunityMembersTable.userId, userId))).limit(1); return row ?? null; }

router.get("/fan-communities/:id/broadcasts", requireAuth, async (req, res): Promise<void> => { const communityId = id(req.params.id); if (!communityId || !(await isMember(communityId, req.dbUser!.id))) { res.status(403).json({ error: "not_member" }); return; } res.json(await db.select().from(fanBroadcastsTable).where(eq(fanBroadcastsTable.communityId, communityId)).orderBy(desc(fanBroadcastsTable.createdAt)).limit(50)); });
router.post("/fan-communities/:id/broadcasts", requireAuth, async (req, res): Promise<void> => { const communityId = id(req.params.id); const parsed = z.object({ title: z.string().trim().min(1).max(100), body: z.string().trim().min(1).max(2000) }).safeParse(req.body); const member = communityId ? await isMember(communityId, req.dbUser!.id) : null; if (!communityId || !parsed.success || member?.role !== "OWNER") { res.status(403).json({ error: "owner_required" }); return; } const [row] = await db.insert(fanBroadcastsTable).values({ communityId, authorUserId: req.dbUser!.id, ...parsed.data }).returning(); res.status(201).json(row); });
router.get("/fan-communities/:id/missions", requireAuth, async (req, res): Promise<void> => { const communityId = id(req.params.id); if (!communityId || !(await isMember(communityId, req.dbUser!.id))) { res.status(403).json({ error: "not_member" }); return; } res.json(await db.select().from(fanMissionsTable).where(and(eq(fanMissionsTable.communityId, communityId), eq(fanMissionsTable.status, "ACTIVE"))).orderBy(desc(fanMissionsTable.createdAt))); });
router.post("/fan-communities/:id/missions", requireAuth, async (req, res): Promise<void> => { const communityId = id(req.params.id); const parsed = z.object({ title: z.string().trim().min(1).max(100), description: z.string().trim().min(1).max(1000) }).safeParse(req.body); const member = communityId ? await isMember(communityId, req.dbUser!.id) : null; if (!communityId || !parsed.success || member?.role !== "OWNER") { res.status(403).json({ error: "owner_required" }); return; } const [row] = await db.insert(fanMissionsTable).values({ communityId, ...parsed.data }).returning(); res.status(201).json(row); });
router.post("/fan-missions/:id/join", requireAuth, async (req, res): Promise<void> => { const missionId = id(req.params.id); if (!missionId) { res.status(400).json({ error: "invalid" }); return; } const [mission] = await db.select({ communityId: fanMissionsTable.communityId }).from(fanMissionsTable).where(and(eq(fanMissionsTable.id, missionId), eq(fanMissionsTable.status, "ACTIVE"))).limit(1); if (!mission || !(await isMember(mission.communityId, req.dbUser!.id))) { res.status(403).json({ error: "not_member" }); return; } await db.insert(fanMissionParticipantsTable).values({ missionId, userId: req.dbUser!.id }).onConflictDoNothing(); res.json({ joined: true }); });
export default router;
