import { Router, type IRouter } from "express";
import usersRouter from "./users";
import friendsRouter from "./friends";
import roomsRouter from "./rooms";
import messagesRouter from "./messages";
import invitesRouter from "./invites";
import blockedRouter from "./blocked";
import callsRouter from "./calls";
import storageRouter from "./storage";
import dungeonsRouter from "./dungeons";
import lifeQuestsRouter from "./lifeQuests";
import battlesRouter from "./battles";
import personaRouter from "./persona";
import clansRouter from "./clans";
import clanWarsRouter from "./clanWars";
import questsRouter from "./quests";
import playModeRouter from "./playMode";
import starFeedRouter from "./starFeed";
import walletsRouter from "./wallets";
import torimiaRouter from "./torimia";
import presenceRouter from "./presence";
import dailyTalkRewardRouter from "./dailyTalkReward";
import pvtRouter from "./pvt";
import anotherMeRouter from "./anotherMe";
import officialAccountsRouter from "./officialAccounts";
import knowledgeRouter from "./knowledge";
import realtimeRouter from "./realtime";
import fanCommunitiesRouter from "./fanCommunities";
import fanCommunityProgramsRouter from "./fanCommunityPrograms";
import starFeedAdminRouter from "./starFeedAdmin";
import searchAdminRouter from "./searchAdmin";
import nftCollectionsRouter from "./nftCollections";

const router: IRouter = Router();

router.use(usersRouter);
router.use(friendsRouter);
router.use(roomsRouter);
router.use(messagesRouter);
router.use(invitesRouter);
router.use(blockedRouter);
router.use(callsRouter);
router.use(storageRouter);
router.use(dungeonsRouter);
router.use(lifeQuestsRouter);
router.use(battlesRouter);
router.use(personaRouter);
router.use(clansRouter);
router.use(clanWarsRouter);
router.use(questsRouter);
router.use(playModeRouter);
router.use(starFeedRouter);
router.use(walletsRouter);
router.use(torimiaRouter);
router.use(presenceRouter);
router.use(dailyTalkRewardRouter);
router.use(pvtRouter);
router.use(anotherMeRouter);
router.use(officialAccountsRouter);
router.use(knowledgeRouter);
router.use(realtimeRouter);
router.use(fanCommunitiesRouter);
router.use(fanCommunityProgramsRouter);
router.use(starFeedAdminRouter);
router.use(searchAdminRouter);
router.use(nftCollectionsRouter);

export default router;
