import { integer, jsonb, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";
import { usersTable } from "./users";
import type { PersonaStats } from "./persona";

/**
 * Life Quest themes — everyday-life simulation settings. A quest is generated
 * around one theme. `daily` is the catch-all "ordinary choices" theme.
 */
export type LifeQuestTheme =
  | "work"
  | "relationship"
  | "money"
  | "health"
  | "study"
  | "conflict"
  | "startup"
  | "daily";

export const LIFE_QUEST_THEMES: LifeQuestTheme[] = [
  "work",
  "relationship",
  "money",
  "health",
  "study",
  "conflict",
  "startup",
  "daily",
];

export type LifeQuestStatus = "active" | "completed" | "failed";

/** How risky/bold a choice is — surfaced in the UI, not a correctness label. */
export type LifeQuestRiskLevel = "low" | "medium" | "high";

/**
 * A single pre-generated choice within a stage. `statChanges` only ever uses the
 * seven {@link PersonaStats} keys; it is applied to the persona when chosen.
 * `resultText` is shown after picking — no AI call is made at choice time.
 */
export interface LifeQuestChoice {
  id: string;
  label: string;
  description: string;
  resultText: string;
  statChanges: Partial<PersonaStats>;
  riskLevel: LifeQuestRiskLevel;
}

/**
 * One stage of a Life Quest. Stages are authored up-front (all at quest start)
 * and played in order. `chosenChoiceId` records the player's pick once made.
 */
export interface LifeQuestStage {
  stageNumber: number;
  title: string;
  situation: string;
  choices: LifeQuestChoice[];
  chosenChoiceId?: string;
}

/**
 * A single-player "Life Quest": an everyday-life decision simulation whose
 * choices grow the user's "Another Me" persona. The entire scenario (all stages
 * + choices + results + stat changes) is generated by AI ONCE at creation; the
 * rest of the run is pure data with no further AI calls.
 */
export const lifeQuestsTable = pgTable("life_quests", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id")
    .notNull()
    .references(() => usersTable.id, { onDelete: "cascade" }),
  title: text("title").notNull(),
  theme: text("theme").$type<LifeQuestTheme>().notNull(),
  goal: text("goal").notNull(),
  summary: text("summary").notNull().default(""),
  currentStageIndex: integer("current_stage_index").notNull().default(0),
  status: text("status").$type<LifeQuestStatus>().notNull().default("active"),
  stages: jsonb("stages").$type<LifeQuestStage[]>().notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
  completedAt: timestamp("completed_at", { withTimezone: true }),
});

export type LifeQuest = typeof lifeQuestsTable.$inferSelect;
