import React from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { Feather } from "@expo/vector-icons";
import { useColors } from "@/hooks/useColors";
import { useOfficialAiAdmin } from "@/hooks/useOfficialAiAdmin";

const statusLabel: Record<string, string> = { draft: "초안", review_required: "검토 필요", approved: "승인됨", published: "게시됨", suspended: "중지됨", archived: "보관" };

export default function OfficialAiAccountsScreen() {
  const colors = useColors();
  const router = useRouter();
  const { data, isLoading, isError, refetch, create } = useOfficialAiAdmin();
  const [showCreate, setShowCreate] = React.useState(false);
  const [form, setForm] = React.useState({ slug: "", displayName: "", description: "" });
  return <ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={styles.container}>
    <View style={styles.header}><View><Text style={[styles.title, { color: colors.foreground }]}>공식 AI 계정</Text><Text style={[styles.subtitle, { color: colors.mutedForeground }]}>비비를 포함한 모든 공식 AI 서비스를 관리합니다.</Text></View><Pressable onPress={() => void refetch()} style={[styles.refresh, { borderColor: colors.border }]}><Feather name="refresh-cw" size={16} color={colors.primary} /></Pressable></View>
    <Pressable onPress={() => setShowCreate((value) => !value)} style={[styles.createButton, { backgroundColor: colors.primary }]}><Text style={{ color: colors.primaryForeground }}>{showCreate ? "생성 취소" : "공식 AI 계정 만들기"}</Text></Pressable>
    {showCreate ? <View style={[styles.form, { backgroundColor: colors.card, borderColor: colors.border }]}><TextInput placeholder="slug (예: bible_coach)" placeholderTextColor={colors.mutedForeground} value={form.slug} onChangeText={(value) => setForm((v) => ({ ...v, slug: value }))} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} /><TextInput placeholder="표시 이름" placeholderTextColor={colors.mutedForeground} value={form.displayName} onChangeText={(value) => setForm((v) => ({ ...v, displayName: value }))} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} /><TextInput placeholder="설명 (선택)" placeholderTextColor={colors.mutedForeground} value={form.description} onChangeText={(value) => setForm((v) => ({ ...v, description: value }))} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} /><Pressable disabled={create.isPending || !form.slug || !form.displayName} onPress={() => void create.mutateAsync(form).then(() => { setForm({ slug: "", displayName: "", description: "" }); setShowCreate(false); })} style={[styles.createButton, { backgroundColor: colors.secondary, opacity: create.isPending || !form.slug || !form.displayName ? 0.5 : 1 }]}><Text style={{ color: colors.foreground }}>{create.isPending ? "저장 중…" : "초안으로 저장"}</Text></Pressable></View> : null}
    {isLoading ? <ActivityIndicator color={colors.primary} /> : isError ? <View style={[styles.empty, { borderColor: colors.border }]}><Text style={{ color: colors.foreground }}>공식 AI 계정을 불러오지 못했습니다.</Text><Pressable onPress={() => void refetch()}><Text style={{ color: colors.primary }}>다시 시도</Text></Pressable></View> : (data ?? []).length === 0 ? <View style={[styles.empty, { borderColor: colors.border }]}><Feather name="cpu" size={24} color={colors.mutedForeground} /><Text style={{ color: colors.foreground }}>등록된 공식 AI 계정이 없습니다.</Text></View> : (data ?? []).map((item) => <Pressable key={item.id} onPress={() => router.push(`/admin/ai-accounts/${item.id}` as never)} style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={styles.cardHeader}><View style={[styles.avatar, { backgroundColor: colors.primary + "22" }]}><Feather name="cpu" size={20} color={colors.primary} /></View><View style={styles.cardMain}><Text style={[styles.cardTitle, { color: colors.foreground }]}>{item.displayName}</Text><Text style={[styles.slug, { color: colors.mutedForeground }]}>@{item.slug} · {item.accountKind}</Text></View><Text style={[styles.status, { color: colors.primary }]}>{statusLabel[item.status] ?? item.status}</Text></View><Text style={[styles.description, { color: colors.mutedForeground }]}>{item.description ?? "설명이 아직 등록되지 않았습니다."}</Text><View style={styles.meta}><Text style={{ color: colors.mutedForeground }}>Knowledge: {item.knowledgeTenantId ?? "연결 안 됨"}</Text><Feather name="chevron-right" size={17} color={colors.mutedForeground} /></View></Pressable>)}
  </ScrollView>;
}

const styles = StyleSheet.create({ container: { padding: 18, gap: 12 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, title: { fontSize: 23, fontWeight: "800" }, subtitle: { fontSize: 12, marginTop: 4 }, refresh: { borderWidth: 1, borderRadius: 10, padding: 10 }, createButton: { borderRadius: 10, minHeight: 42, alignItems: "center", justifyContent: "center", paddingHorizontal: 14 }, form: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 9 }, input: { minHeight: 42, borderWidth: 1, borderRadius: 10, paddingHorizontal: 11 }, card: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 12 }, cardHeader: { flexDirection: "row", alignItems: "center", gap: 10 }, avatar: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center" }, cardMain: { flex: 1, gap: 3 }, cardTitle: { fontSize: 16, fontWeight: "700" }, slug: { fontSize: 11 }, status: { fontSize: 11, fontWeight: "700" }, description: { fontSize: 12, lineHeight: 18 }, meta: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, empty: { borderWidth: 1, borderRadius: 16, minHeight: 150, alignItems: "center", justifyContent: "center", gap: 10 } });
